linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  disable:
    - exhaustruct # TODO
    - gci # TODO
    - gochecknoglobals # TODO
    - gocritic # TODO
    - goerr113 # TODO
    - gofumpt # TODO
    - gomnd # "magic numbers" are essential for stack-based environments
    - ireturn # TODO
    - lll # TODO
    - nlreturn # TODO
    - nonamedreturns # TODO
    - paralleltest # TODO
    - revive # TODO
    - rowserrcheck # disabled because of generics. https://github.com/golangci/golangci-lint/issues/2649
    - stylecheck # TODO
    - tagliatelle # disabled because we explicitly do not want this
    - testpackage # TODO
    - thelper # TODO
    - unparam # TODO
    - varnamelen # TODO
    - wastedassign # disabled because of generics. https://github.com/golangci/golangci-lint/issues/2649
    - whitespace # TODO
    - wrapcheck # TODO
    - wsl # TODO

linters-settings:
  cyclop:
    max-complexity: 15
  funlen:
    lines: 100

issues:
  exclude:
    - Line contains TODO/BUG/FIXME # godox
  exclude-rules:
    - path: pkg/ssh_connection/ssh_connection.go
      text: Use of ssh InsecureIgnoreHostKey should be audited
    - path: _test\.go
      linters:
        - funlen
        - dupl
