linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  disable:
    # must-disable
    - gomnd # "magic numbers" are essential for stack-based environments
    - tagliatelle # disabled because we explicitly do not want this
    - unparam # explicitly disabled due to some not-technically-false-positives but suggestions that hurt consistency
    # deprecated linters
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    # disabled due to personal preference
    - depguard
    - exhaustruct
    - gomnd
    - nlreturn
    - tagliatelle
    - unparam
    - wrapcheck
    - wsl
    # disabled because of generics. https://github.com/golangci/golangci-lint/issues/2649
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    # TODO: evaluate
    - errcheck
    - gocognit
    - goerr113
    - inamedparam
    - ireturn
    - lll
    - paralleltest
    - perfsprint
    - revive
    - testifylint
    - testpackage
    - varnamelen


linters-settings:
  cyclop:
    max-complexity: 17
  funlen:
    lines: 100
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/sapslaj/zonepop)
      - blank
      - dot
    custom-order: true

issues:
  exclude:
    - Line contains TODO/BUG/FIXME # godox
    - "`L' should not be capitalized" # gocritic
    - and that stutters # revive
  exclude-rules:
    - path: pkg/sshconnection/sshconnection.go
      text: Use of ssh InsecureIgnoreHostKey should be audited
    - path: _test\.go
      linters:
        - dupl
        - exhaustive
        - forcetypeassert
        - funlen
    - path: main\.go
      linters:
        # flags are known globals
        - gochecknoglobals
    - path: config/configtypes/configtypes\.go
      linters:
        # configtypes contains known acceptable globals
        - gochecknoglobals
    - path: source/vyos/neighbor\.go
      text: ValidNUDs is a global variable
