linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
  disabled:
    - rowserrcheck # disabled because of generics. https://github.com/golangci/golangci-lint/issues/2649
  presets:
    - bugs
    - comment
    # - complexity
    # - error
    # - format
    # - metalinter
    - module
    - performance
    - sql
    # - style
    # - test
    # - unused

issues:
  exclude:
    - Line contains TODO/BUG/FIXME # godox
  exclude-rules:
    - path: pkg/ssh_connection/ssh_connection.go
      text: Use of ssh InsecureIgnoreHostKey should be audited
