linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
  disabled:
    - rowserrcheck # disabled because of generics. https://github.com/golangci/golangci-lint/issues/2649
  presets:
    # - bugs
    # - comment
    # - complexity
    # - error
    # - format
    # - metalinter
    - module
    - performance
    - sql
    # - style
    # - test
    # - unused
