package hostsfile

import (
	"context"
	"os"
	"path"
	"testing"

	"github.com/sapslaj/zonepop/config/configtypes"
	"github.com/sapslaj/zonepop/endpoint"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestHostsFileProvider(t *testing.T) {
	t.Parallel()

	tmpdir := t.TempDir()

	expect := `# Generated by ZonePop
192.0.2.1	test-host
2001:db8::1	test-host
`

	p, err := NewHostsFileProvider(
		HostsFileProviderConfig{
			File: path.Join(tmpdir, "hosts"),
		},
		configtypes.DefaultEndpointFilterFunc,
	)
	require.NoError(t, err)

	err = p.UpdateEndpoints(context.Background(), []*endpoint.Endpoint{
		{
			Hostname:  "test-host",
			IPv4s:     []string{"192.0.2.1"},
			IPv6s:     []string{"2001:db8::1"},
			RecordTTL: 60,
		},
	})
	require.NoError(t, err)

	data, err := os.ReadFile(path.Join(tmpdir, "hosts"))
	require.NoError(t, err)

	assert.Equal(t, expect, string(data))
}
