package http

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/sapslaj/zonepop/config/configtypes"
	"github.com/sapslaj/zonepop/endpoint"
	"github.com/sapslaj/zonepop/pkg/rdns"
)

func TestHTTPProvider(t *testing.T) {
	t.Parallel()

	p, err := NewHTTPProvider(
		HTTPProviderConfig{},
		configtypes.DefaultEndpointFilterFunc,
		configtypes.DefaultEndpointFilterFunc,
	)
	require.NoError(t, err)

	server := httptest.NewServer(http.DefaultServeMux)
	defer server.Close()

	res, err := http.Get(server.URL + "/endpoints/forward")
	require.NoError(t, err)
	bodyData, err := io.ReadAll(res.Body)
	require.NoError(t, err)
	res.Body.Close()
	var emptyResult []endpoint.Endpoint
	err = json.Unmarshal(bodyData, &emptyResult)
	require.NoError(t, err)

	assert.Len(t, emptyResult, 0)

	p.UpdateEndpoints(context.Background(), []*endpoint.Endpoint{
		{
			Hostname:  "test-host",
			IPv4s:     []string{"192.0.2.1"},
			IPv6s:     []string{"2001:db8::1"},
			RecordTTL: 60,
		},
	})

	res, err = http.Get(server.URL + "/endpoints/forward")
	require.NoError(t, err)
	bodyData, err = io.ReadAll(res.Body)
	require.NoError(t, err)
	res.Body.Close()
	var populatedResultForward []endpoint.Endpoint
	err = json.Unmarshal(bodyData, &populatedResultForward)
	require.NoError(t, err)

	assert.Len(t, populatedResultForward, 1)
	assert.Equal(t, []endpoint.Endpoint{
		{
			Hostname:  "test-host",
			IPv4s:     []string{"192.0.2.1"},
			IPv6s:     []string{"2001:db8::1"},
			RecordTTL: 60,
		},
	}, populatedResultForward)

	res, err = http.Get(server.URL + "/endpoints/reverse-ipv4")
	require.NoError(t, err)
	bodyData, err = io.ReadAll(res.Body)
	require.NoError(t, err)
	res.Body.Close()
	var populatedResultReverse []rdns.PTRRecord
	err = json.Unmarshal(bodyData, &populatedResultReverse)
	require.NoError(t, err)

	assert.Len(t, populatedResultReverse, 1)
	assert.Equal(t, []rdns.PTRRecord{
		{
			Endpoint: &endpoint.Endpoint{
				Hostname:  "test-host",
				IPv4s:     []string{"192.0.2.1"},
				IPv6s:     []string{"2001:db8::1"},
				RecordTTL: 60,
			},
			Hostname:              "test-host",
			AutoGeneratedHostname: false,
			FullHostname:          "test-host",
			Address:               "192.0.2.1",
			AddressKind:           rdns.AddressKindIPv4,
			DomainName:            "1.2.0.192.in-addr.arpa.",
			RFC1035DomainName:     "1.2.0.192",
		},
	}, populatedResultReverse)

	res, err = http.Get(server.URL + "/endpoints/reverse-ipv6")
	require.NoError(t, err)
	bodyData, err = io.ReadAll(res.Body)
	require.NoError(t, err)
	res.Body.Close()
	populatedResultReverse = []rdns.PTRRecord{}
	err = json.Unmarshal(bodyData, &populatedResultReverse)
	require.NoError(t, err)

	assert.Len(t, populatedResultReverse, 1)
	assert.Equal(t, []rdns.PTRRecord{
		{
			Endpoint: &endpoint.Endpoint{
				Hostname:  "test-host",
				IPv4s:     []string{"192.0.2.1"},
				IPv6s:     []string{"2001:db8::1"},
				RecordTTL: 60,
			},
			Hostname:              "test-host",
			AutoGeneratedHostname: false,
			FullHostname:          "test-host",
			Address:               "2001:db8::1",
			AddressKind:           rdns.AddressKindIPv6,
			DomainName:            "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa.",
			RFC1035DomainName:     "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2",
		},
	}, populatedResultReverse)
}
